# Site setings
name: 'Sivamuthu Kumar'
description: 'Horace is a simple Jekyll theme for writers and bloggers. Explore it yourself.'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://ksivamuthu.netlify.com/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Sivamuthu Kumar'
  image: 'authorimage.jpg'
  greetings: 'Hello Everyone!'
  description: 'Sivamuthu Kumar - Focusing on goals 🎯 | Dad of princess | 💕@Depikarajendran | Speaker | Architect | God Driven 😇 | Code Streamer https://twitch.tv/ksivamuthu'
  bio: 'Sivamuthu Kumar - Focusing on goals 🎯 | Dad of princess | 💕@Depikarajendran | Speaker | Architect | God Driven 😇 | Code Streamer https://twitch.tv/ksivamuthu'

# Contact form setings
email: sivamuthukumar07@gmail.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'ksivamuthu'
facebook: 'ksivamuthu'
github: 'ksivamuthu'
codepen: 'ksivamuthu'
medium: '@ksivamuthu'
linkedin: 'ksivamuthu'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Talks
    url: /talks/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
